export enum ErrorEnum {
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  USER_EMAIL_EXIST = 'USER_EMAIL_EXIST',
}
