// src/modules/users/admin/admin.service.ts
import { Injectable } from '@nestjs/common';
import { DataSource, Repository } from 'typeorm';
import { InjectRepository } from '@nestjs/typeorm';
import { randomUUID } from 'crypto';
import { NotFoundException } from '@nestjs/common';

import { Showtime } from 'src/modules/tickets/entities/showtime.entity';
import { ShowtimeSeat, SeatStatus } from 'src/modules/tickets/entities/showtime-seat.entity';
import { SeatTemplate } from 'src/modules/tickets/entities/template-seat.entity';
import type { SeatType } from 'src/modules/tickets/entities/showtime-seat.entity';
import { SaveSeatTemplateDto } from './dto/save-seat-template.dto';
import { CreateShowtimeDto } from './dto/create-showtime.dto';
import { RedisService } from 'src/infrastructure/redis/redis.service'; // Adjust path if needed

@Injectable()
export class AdminService {
  constructor(
    private dataSource: DataSource,
    @InjectRepository(SeatTemplate)
    private readonly seatTemplateRepo: Repository<SeatTemplate>,
    @InjectRepository(Showtime)
    private readonly showtimeRepo: Repository<Showtime>,
    @InjectRepository(ShowtimeSeat)
    private readonly showtimeSeatRepo: Repository<ShowtimeSeat>,
    private readonly redisService: RedisService, // <-- Inject Redis Service
  ) {}

  // --- UPDATE: Modify createShowtime to accept new fields ---
  async createShowtime(dto: any /* Or your updated CreateShowtimeDto */) {
    return await this.dataSource.transaction(async (manager) => {
      const start = new Date(dto.startTime);
      const durationMinutes = dto.durationMinutes ?? 120;
      const end = new Date(start.getTime() + durationMinutes * 60_000);
      const cols = dto.cols;
      const totalSeats = dto.rows * cols;

      const showtime = manager.create(Showtime, {
        movieTitle: dto.movieTitle,
        description: dto.description, // <-- NEW
        bannerImage: dto.bannerImage, // <-- NEW
        startTime: start,
        endTime: end,
        theatreName: dto.theatreName ?? 'Main Theatre',
        hallName: dto.hallName ?? 'Main Hall',
        projectionType: dto.projectionType ?? '2D',
        ageRating: dto.ageRating ?? 'T16',
        totalSeats,
        availableSeats: totalSeats,
      });

      const savedShow = await manager.save(showtime);

      // ... rest of the existing seat generation logic ...
      return savedShow;
    });
  }

  async saveSeatTemplate(dto: SaveSeatTemplateDto) {
    return await this.dataSource.transaction(async (manager) => {
      const templateId = randomUUID();
      const templateName = dto.templateName ?? 'Default Layout';
      const hallName = dto.hallName ?? 'Main Hall';

      const seats = dto.layout.map((seat) => ({
        templateId,
        templateName,
        hallName,
        seatId: seat.id, // <-- Capture the exact frontend ID
        rowNumber: seat.gridRow,
        colNumber: seat.gridCol,
        type: seat.type,
        isBlocked: seat.isBlocked
      }));

      await manager.insert(SeatTemplate, seats);
      return { templateId, templateName, savedSeats: seats.length };
    });
  }

  async getTemplateDetails(templateId: string) {
    const seats = await this.seatTemplateRepo.find({ where: { templateId } });
    
    if (!seats || seats.length === 0) {
      throw new NotFoundException(`Template with ID ${templateId} not found`);
    }

    // Calculate the grid size based on the highest row/col numbers saved in the DB
    const rows = Math.max(...seats.map((s) => s.rowNumber)) + 1;
    const columns = Math.max(...seats.map((s) => s.colNumber)) + 1;

    return {
      hallName: seats[0].hallName,
      dimensions: {
        rows,
        columns,
      },
    };
  }

  async applyTemplateToShowtime(showtimeId: string, templateId: string) {
    // 1. Fetch the blueprint seats from your template table
    const templateSeats = await this.seatTemplateRepo.find({ where: { templateId } });

    if (!templateSeats || templateSeats.length === 0) {
      throw new Error(`Template ${templateId} has no seats configured.`);
    }

    // ---> THE FIX: Wipe the floor clean! <---
      // Delete the default solid block of seats generated by createShowtime
      await this.showtimeSeatRepo.delete({ showtimeId });

    // Build the blueprint array
      const seatsData = templateSeats.map(ts => ({
        showtimeId: showtimeId,               
        showtime: { id: showtimeId },         
        seatNumber: ts.seatId,
        type: ts.type,
        status: ts.isBlocked ? SeatStatus.UNAVAILABLE : SeatStatus.AVAILABLE,
        section: ts.hallName || 'Main',
        
        // ---> THE FIX: Copy exact grid coordinates so gaps are preserved! <---
        rowNumber: ts.rowNumber,
        colNumber: ts.colNumber
      }));

      // Create and Save
      const showtimeSeatsToInsert = this.showtimeSeatRepo.create(seatsData as any);

    // 3. Batch save all generated seats to the database
    await this.showtimeSeatRepo.save(showtimeSeatsToInsert);
    
    return { success: true, seatsGenerated: showtimeSeatsToInsert.length };
  }

  async getSeatTemplates() {
    const templates = await this.seatTemplateRepo
      .createQueryBuilder('st')
      .select(['st.templateId', 'st.templateName', 'st.hallName'])
      .distinct(true)
      .getRawMany();

    return templates.map((row) => ({
      templateId: row.st_templateId,
      templateName: row.st_templateName,
      hallName: row.st_hallName,
    }));
  }

  // --- NEW: Delete Template ---
  async deleteSeatTemplate(templateId: string) {
    // Because your template seats share a common templateId, 
    // deleting all rows with this ID effectively deletes the template.
    const result = await this.seatTemplateRepo.delete({ templateId });
    
    if (result.affected === 0) {
      throw new NotFoundException('Template not found');
    }
    return { success: true, message: 'Template deleted successfully' };
  }

  private getSection(col: number, totalCols: number): 'left' | 'center' | 'right' {
    if (col < 4) return 'right';
    if (col >= totalCols - 4) return 'left';
    return 'center';
  }

  async getShowtimes() {
    return await this.showtimeRepo.find({ order: { startTime: 'DESC' } });
  }

  // --- NEW: Update Showtime Details ---
  async updateShowtime(id: string, dto: any) {
    const showtime = await this.showtimeRepo.findOne({ where: { id } });
    if (!showtime) throw new NotFoundException('Showtime not found');

    if (dto.movieTitle) showtime.movieTitle = dto.movieTitle;
    if (dto.description !== undefined) showtime.description = dto.description;
    if (dto.bannerImage !== undefined) showtime.bannerImage = dto.bannerImage;
    if (dto.startTime) showtime.startTime = new Date(dto.startTime);

    return await this.showtimeRepo.save(showtime);
  }

  // --- NEW: Delete Showtime and its Seats ---
  async deleteShowtime(id: string) {
    return await this.dataSource.transaction(async (manager) => {
      // 1. Delete all associated seats first to avoid Foreign Key constraint errors
      await manager.delete(ShowtimeSeat, { showtimeId: id });
      
      // 2. Delete the actual showtime
      const result = await manager.delete(Showtime, { id });
      
      if (result.affected === 0) {
        throw new NotFoundException('Showtime not found');
      }
      return { success: true, message: 'Showtime and associated seats deleted' };
    });
  }

  // --- NEW: Manual Seat Override ---
  async overrideSeatStatus(showtimeId: string, seatId: string, newStatus: string) {
    // 1. Force the PostgreSQL database to update the status
    await this.showtimeSeatRepo.update(
      { showtimeId, seatNumber: seatId },
      { status: newStatus as SeatStatus }, 
    );

    // 2. CRITICAL: If the admin is forcing the seat back to 'AVAILABLE', 
    // we MUST delete any lingering Redis lock so users can actually buy it again.
    if (newStatus === SeatStatus.AVAILABLE) {
      // Assuming your redis method is called 'del' based on our previous fix
      await this.redisService.del(`lock:${showtimeId}:${seatId}`);
    }

    return { success: true, seatId, newStatus };
  }


}
